# Generated by Django 4.1.3 on 2022-11-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBlockAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('form_customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('form_customer_message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Блок "Заявки"',
                'verbose_name_plural': 'Блок "Заявки"',
            },
        ),
        migrations.CreateModel(
            name='LandingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_utp', models.TextField(verbose_name='UTP')),
                ('top_descriptor', models.TextField(verbose_name='Описание utp')),
                ('top_fb_url', models.URLField(verbose_name='Facebook url')),
                ('top_tw_url', models.URLField(verbose_name='Twitter url')),
                ('top_insta_url', models.URLField(verbose_name='Instagram url')),
                ('top_picture', models.ImageField(upload_to='top/', verbose_name='Изображение для блока')),
                ('about_us_header', models.CharField(default='О нас', max_length=100, verbose_name='Название блока')),
                ('about_us_text1', models.TextField(verbose_name='Первая часть текста')),
                ('about_us_text2', models.TextField(verbose_name='Вторая часть текста')),
                ('about_us_picture1', models.ImageField(upload_to='about_us/', verbose_name='Изображение для блока о нас 1')),
                ('about_us_picture2', models.ImageField(upload_to='about_us/', verbose_name='Изображение для блока о нас 2')),
                ('about_us_value', models.TextField(verbose_name='Значение производительности (добавьте единицы измерения)')),
                ('about_us_capacity', models.TextField(verbose_name='Значение объема выполненных работ (добавьте единицы измерения)')),
                ('about_us_employee', models.IntegerField(verbose_name='Значение числа сотрудников')),
                ('products_header', models.CharField(default='Продукция', max_length=100, verbose_name='Название блока')),
                ('products_description', models.TextField(verbose_name='Описание для блока продукции')),
                ('products_first_card_utp', models.TextField(verbose_name='Первая карточка продукции название')),
                ('products_first_card_desc', models.TextField(verbose_name='Первая карточка продукции описание')),
                ('products_second_card_utp', models.TextField(verbose_name='Вторая карточка продукции название')),
                ('products_second_card_desc', models.TextField(verbose_name='Вторая карточка продукции описание')),
                ('products_third_card_utp', models.TextField(verbose_name='Третья карточка продукции название')),
                ('products_third_card_desc', models.TextField(verbose_name='Третья карточка продукции описание')),
                ('benefits_header', models.CharField(default='Почему именно мы?', max_length=100, verbose_name='Название блока')),
                ('benefits_first', models.TextField(verbose_name='Первое преимущество')),
                ('benefits_second', models.TextField(verbose_name='Второе преимущество')),
                ('benefits_third', models.TextField(verbose_name='Третье преимущество')),
                ('benefits_fourth', models.TextField(verbose_name='Четвертое преимущество')),
                ('benefits_fifth', models.TextField(verbose_name='Пятое преимущество')),
                ('benefits_sixth', models.TextField(verbose_name='Шестое преимущество')),
                ('benefits_seventh', models.TextField(verbose_name='Седьмое преимущество')),
                ('gallery_header', models.CharField(default='Галерея', max_length=100, verbose_name='Название блока')),
                ('team_header', models.CharField(default='Наша команда', max_length=100, verbose_name='Название блока')),
                ('form_personal_data', models.FileField(upload_to='uploads/', verbose_name='Соглашение о персональных данных')),
                ('footer_address', models.TextField(verbose_name='Адрес компании')),
                ('footer_email', models.CharField(max_length=100, verbose_name='Email компании')),
                ('fax_footer', models.CharField(max_length=100, verbose_name='Факс компании')),
            ],
            options={
                'verbose_name': 'Настройка лендинга',
                'verbose_name_plural': 'Настройки лендинга',
            },
        ),
        migrations.CreateModel(
            name='ManagersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managers_name', models.CharField(max_length=100, verbose_name='Имя менеджера')),
                ('managers_email', models.CharField(max_length=100, verbose_name='Емэйл для отправки почты')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_description', models.TextField(verbose_name='Описание продукта')),
                ('product_property', models.CharField(max_length=100, verbose_name='Свойства продукта (добавьте единицы измерения)')),
                ('product_photo', models.ImageField(upload_to='', verbose_name='Фото продукта')),
                ('products_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='food_packaging_admin.landingmodel')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='GalleryImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='Фото для галереи')),
                ('gallery_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='food_packaging_admin.landingmodel')),
            ],
            options={
                'verbose_name': 'Фото для галереи',
                'verbose_name_plural': 'Фото для галереи',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='Имя и фамилия сотрудника')),
                ('employee_position', models.CharField(max_length=100, verbose_name='Должность сотрудника')),
                ('employee_photo', models.ImageField(upload_to='employee/', verbose_name='Фото сотрудника')),
                ('employee_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='food_packaging_admin.landingmodel')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
