# Generated by Django 4.1.3 on 2022-11-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_packaging_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBlockAdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('form_customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('form_customer_message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Блок "Заявки"',
                'verbose_name_plural': 'Блок "Заявки"',
            },
        ),
    ]
