# Generated by Django 4.1.3 on 2022-11-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_packaging_admin', '0003_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='ManagersModel',
        ),
    ]
